---
name: changelog and linters

on: [workflow_call]  # allow this workflow to be called from other workflows

jobs:
  linters:
    uses: ./.github/workflows/tox.yml
    with:
      envname: ""
      labelname: "lint"
      checkout_path: ${{ env.source_directory }}
      checkout_ref: ${{  github.event.pull_request.head.sha }}
      checkout_fetch_depth: "0"
