name: tox
on:
  workflow_call:
    inputs:
      envname:
        description: Tox environment name to use to limit the run
        required: false
        type: string
        default: ""
      labelname:
        description: Tox label to use to limit the run
        required: false
        type: string
        default: ""
      checkout_path:
        description: Path to pass to checkout action
        required: false
        type: string
        default: ${{ env.source_directory }}
      checkout_ref:
        description: Repository reference to pass to checkout action
        required: false
        type: string
        default: ""
      checkout_fetch_depth:
        description: Fetch depth to pass to checkout action
        required: false
        type: integer
        default: "0"
jobs:
  tox:
    runs-on: ubuntu-latest
    name: Run Tox based code tests
    steps:
      - name: Code checkout
        if: ${{ ! inputs.checkout_ref }}
        uses: actions/checkout@v3

      - name: Code checkout with parameters
        if: ${{ inputs.checkout_ref }}
        uses: actions/checkout@v3
        with:
          path: ${{ inputs.checkout_path }}
          ref: ${{ inputs.checkout_ref }}
          fetch-depth: ${{ inputs.checkout_fetch_depth }}

      - name: Run tests
        uses: ansible-network/github_actions/.github/actions/tox@main
        with:
          path: "."
          tox_envlist: ${{ inputs.envname }}
          tox_labellist: ${{ inputs.labelname }}
